const modal=document.querySelector('#modal'),content=document.querySelector('#modal-content');
function openModal(title,body){content.innerHTML='<span class="demo-badge">Hotel OS · Демонстраційна сторінка</span><h2>'+title+'</h2>'+body;modal.showModal();}
document.querySelector('.close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
const actions={contacts:['Контакти Hotel OS','<p>Контактні дані команди ще не додані. Перед запуском сторінки тут потрібно вказати актуальні email і телефон.</p>'],terms:['Умови використання','<p>Затверджені умови використання ще не додані. Демонстраційні інтерфейси не створюють бронювань, не приймають оплат і не надають доступу до сервісу.</p>']};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b){if(b.dataset.action==='login'||b.dataset.action==='trial'||b.dataset.action==='demo'){window.location.href='/dashboard/';return}if(b.dataset.action==='calendar'){openModal('Один календар. Увесь готель.','<p>Натисніть на бронювання, щоб переглянути інформацію про гостя.</p>'+document.querySelector('#calendar .calendar').outerHTML);}else{const a=actions[b.dataset.action];if(a)openModal(...a)}}const g=e.target.closest('[data-guest]');if(g){openModal(g.dataset.guest,'<p>Приклад бронювання · Вересень 2026</p><div class="guest-stats"><div><b>2</b><small>гості</small></div><div><b>3</b><small>ночі</small></div><div><b>8 400 ₴</b><small>загальна сума</small></div></div><p><span class="pill">Оплачено</span></p><p>Побажання: тихий номер, пізній заїзд, сніданок.</p><p>Це демонстраційні дані.</p>')}if(e.target.closest('#modal-pricing'))modal.close();});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-guest]')){e.preventDefault();e.target.click()}});
const responses={today:['Що сьогодні важливого?','<p>Сьогодні у вас <b>7 заїздів і 4 виїзди.</b></p><p>Номер <b>204</b> ще потрібно прибрати.</p><p>Два бронювання мають неоплачений залишок на загальну суму <b>4 800 ₴.</b></p><p>Перший гість очікується приблизно о <b>13:30.</b></p>'],guests:['Хто наші найкращі постійні гості?','<p><b>18 гостей</b> проживали у вас щонайменше три рази за останні 12 місяців.</p><p>Разом вони витратили <b>184 000 ₴.</b></p>'],rooms:['Які номери вільні на ці вихідні?','<p>З п’ятниці до неділі доступні номери <b>103, 204 та 205.</b></p><p>Перегляньте календар, щоб обрати номер і перевірити дати.</p>']};
document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-prompt]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const [q,a]=responses[b.dataset.prompt];document.querySelector('#ai-question').textContent=q;document.querySelector('#ai-response').innerHTML='<span class="tiny">✦</span>'+a;}));
document.querySelector('#ai-response').setAttribute('aria-live','polite');
document.querySelector('#clean-ready').addEventListener('click',e=>{const card=e.target.closest('article');card.querySelector('.pill').textContent='Готовий ✓';card.querySelector('p').textContent='Марія · Номер підготовлений';e.target.textContent='Номер готовий ✓';e.target.disabled=true;});
const menu=document.querySelector('.menu');menu.addEventListener('click',()=>{const expanded=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!expanded));document.querySelector('nav').classList.toggle('nav-open',!expanded)});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('nav').classList.remove('nav-open');menu.setAttribute('aria-expanded','false')}));
